### ISSUE TITLE
Unbenotete Leistungen

### ISSUE THREAD

**Issue by Theratherverydarkestlordever** [Idontker/baGrad4LA#7]
Unbenotete Leistungen erlauben, da manche Fächer, v.a. Praktika, ohne Note bestanden werden

**Comment by Idontker** [comment]
Ist auf dem smartFachPanels branch implementiert ;-) Zuvor konnte man eine Note angeben, die mit 0 gewichtet wurde. 

Finde sich sehr bald auf dem Main wieder!
Vielleicht noch heute :D
