### ISSUE TITLE
Auswahlen spezifizieren

### ISSUE THREAD

**Issue by Theratherverydarkestlordever** [Idontker/baGrad4LA#8]
Da man am Anfang seine Fächer angibt, wäre es sicher möglich, bei den Didaktiken statt "Fach 1" und "Fach 2" die Fachnamen zu verwenden

**Comment by Idontker** [comment]
Ist bereits implementiert ;-) Finde sich sehr bald auf dem Main wieder!
Vielleicht noch heute :D
